# version: "3.9"

# services:
#   django:
#     build:
#       context: ./social-media
#     container_name: django
#     command: >
#       sh -c "cd /root/my_app/apps &&
#                 python manage.py wait_for_db &&
#                 python manage.py makemigrations &&
#                 python manage.py migrate &&
#                 python manage.py runserver 0.0.0.0:8000"
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

#   db:
#     image: postgres
#     ports:
#       - "5433:5432"
#     environment:
#       - "POSTGRES_HOST_AUTH_METHOD=trust"
#     container_name: db

#   frontend:
#     build:
#       context: ./frontend-app
#     ports:
#       - "3000:3000"

version: "3.9"

services:
  django:
    build:
      context: ./social-media
    container_name: django
    command: >
      sh -c "cd /root/my_app/apps &&
                python manage.py wait_for_db &&
                python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    container_name: db

  frontend:
    build:
      context: ./frontend-app
    container_name: frontend
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - django
